// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAttachment = `-- name: CreateAttachment :one
insert into attachments (note_id, object_key, filename, mime_type, size_bytes, status, uploaded_by)
values ($1, $2, $3, $4, $5, 'pending', $6)
returning id, note_id, object_key, filename, mime_type, size_bytes, checksum, status, uploaded_by, created_at, ready_at
`

type CreateAttachmentParams struct {
	NoteID     uuid.UUID
	ObjectKey  string
	Filename   string
	MimeType   string
	SizeBytes  int64
	UploadedBy uuid.UUID
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.NoteID,
		arg.ObjectKey,
		arg.Filename,
		arg.MimeType,
		arg.SizeBytes,
		arg.UploadedBy,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.NoteID,
		&i.ObjectKey,
		&i.Filename,
		&i.MimeType,
		&i.SizeBytes,
		&i.Checksum,
		&i.Status,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.ReadyAt,
	)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :execrows
delete from attachments where id = $1 and note_id = $2
`

type DeleteAttachmentParams struct {
	ID     uuid.UUID
	NoteID uuid.UUID
}

func (q *Queries) DeleteAttachment(ctx context.Context, arg DeleteAttachmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAttachment, arg.ID, arg.NoteID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAttachmentByID = `-- name: DeleteAttachmentByID :execrows
delete from attachments where id = $1
`

func (q *Queries) DeleteAttachmentByID(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAttachmentByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAttachment = `-- name: GetAttachment :one
select id, note_id, object_key, filename, mime_type, size_bytes, checksum, status, uploaded_by, created_at, ready_at
from attachments
where id = $1 and note_id = $2
`

type GetAttachmentParams struct {
	ID     uuid.UUID
	NoteID uuid.UUID
}

func (q *Queries) GetAttachment(ctx context.Context, arg GetAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachment, arg.ID, arg.NoteID)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.NoteID,
		&i.ObjectKey,
		&i.Filename,
		&i.MimeType,
		&i.SizeBytes,
		&i.Checksum,
		&i.Status,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.ReadyAt,
	)
	return i, err
}

const listNoteAttachments = `-- name: ListNoteAttachments :many
select id, note_id, object_key, filename, mime_type, size_bytes, checksum, status, uploaded_by, created_at, ready_at
from attachments
where note_id = $1 and status = 'ready'
order by created_at
`

func (q *Queries) ListNoteAttachments(ctx context.Context, noteID uuid.UUID) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listNoteAttachments, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.NoteID,
			&i.ObjectKey,
			&i.Filename,
			&i.MimeType,
			&i.SizeBytes,
			&i.Checksum,
			&i.Status,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.ReadyAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleUploads = `-- name: ListStaleUploads :many
select id, object_key
from attachments
where status = 'pending' and created_at < $1
order by created_at
limit $2
`

type ListStaleUploadsParams struct {
	CreatedAt time.Time
	Limit     int32
}

type ListStaleUploadsRow struct {
	ID        uuid.UUID
	ObjectKey string
}

// ListStaleUploads finds abandoned uploads: rows still pending long after the
// presigned URL expired, because the client never finished.
//
// Note this deliberately does NOT treat an unreferenced attachment as an
// orphan. A file attached to a note without being inlined in the body is a
// legitimate case; only an unfinished upload is garbage.
func (q *Queries) ListStaleUploads(ctx context.Context, arg ListStaleUploadsParams) ([]ListStaleUploadsRow, error) {
	rows, err := q.db.Query(ctx, listStaleUploads, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaleUploadsRow{}
	for rows.Next() {
		var i ListStaleUploadsRow
		if err := rows.Scan(&i.ID, &i.ObjectKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAttachmentReady = `-- name: MarkAttachmentReady :one
update attachments
set status = 'ready', ready_at = now(), size_bytes = $2, checksum = $3
where id = $1 and status = 'pending'
returning id, note_id, object_key, filename, mime_type, size_bytes, checksum, status, uploaded_by, created_at, ready_at
`

type MarkAttachmentReadyParams struct {
	ID        uuid.UUID
	SizeBytes int64
	Checksum  *string
}

// MarkAttachmentReady closes the two-phase upload.
//
// Conditional on status = 'pending', so completing twice is not an error the
// second time round and cannot rewrite a verified size.
func (q *Queries) MarkAttachmentReady(ctx context.Context, arg MarkAttachmentReadyParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, markAttachmentReady, arg.ID, arg.SizeBytes, arg.Checksum)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.NoteID,
		&i.ObjectKey,
		&i.Filename,
		&i.MimeType,
		&i.SizeBytes,
		&i.Checksum,
		&i.Status,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.ReadyAt,
	)
	return i, err
}
