// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
)

type Attachment struct {
	ID         uuid.UUID
	NoteID     uuid.UUID
	ObjectKey  string
	Filename   string
	MimeType   string
	SizeBytes  int64
	Checksum   *string
	Status     string
	UploadedBy uuid.UUID
	CreatedAt  time.Time
	ReadyAt    *time.Time
}

type Note struct {
	ID          uuid.UUID
	OwnerUserID uuid.UUID
	Title       string
	Body        string
	Tags        []string
	Version     int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   *time.Time
	SearchTsv   interface{}
}

type NoteShare struct {
	NoteID        uuid.UUID
	PrincipalType string
	PrincipalID   uuid.UUID
	Role          string
	GrantedBy     uuid.UUID
	CreatedAt     time.Time
}

type Team struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TeamMember struct {
	TeamID    uuid.UUID
	UserID    uuid.UUID
	Role      string
	CreatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	DisplayName  string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    *time.Time
}
