// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countNoteAttachments = `-- name: CountNoteAttachments :one
select count(*) from attachments
where note_id = $1 and status = 'ready'
`

func (q *Queries) CountNoteAttachments(ctx context.Context, noteID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNoteAttachments, noteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNote = `-- name: CreateNote :one

insert into notes (owner_user_id, title, body, tags)
values ($1, $2, $3, $4)
returning id, owner_user_id, title, body, tags, version, created_at, updated_at, deleted_at
`

type CreateNoteParams struct {
	OwnerUserID uuid.UUID
	Title       string
	Body        string
	Tags        []string
}

type CreateNoteRow struct {
	ID          uuid.UUID
	OwnerUserID uuid.UUID
	Title       string
	Body        string
	Tags        []string
	Version     int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   *time.Time
}

// Note queries.
//
// Columns are listed explicitly rather than using `select *`: notes carries a
// generated search_tsv, and selecting it would drag the full-text vector of
// every note across the wire for no reason.
func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (CreateNoteRow, error) {
	row := q.db.QueryRow(ctx, createNote,
		arg.OwnerUserID,
		arg.Title,
		arg.Body,
		arg.Tags,
	)
	var i CreateNoteRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Title,
		&i.Body,
		&i.Tags,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getNoteWithAccess = `-- name: GetNoteWithAccess :one
select
    n.id, n.owner_user_id, n.title, n.body, n.tags, n.version,
    n.created_at, n.updated_at, n.deleted_at,
    (case
        when n.owner_user_id = $1 then 3
        else coalesce((
            select max(case s.role
                        when 'editor' then 2
                        when 'viewer' then 1
                        else 0
                       end)
            from note_shares s
            where s.note_id = n.id
              and (
                    (s.principal_type = 'user' and s.principal_id = $1)
                 or (s.principal_type = 'team' and s.principal_id in (
                        select tm.team_id
                        from team_members tm
                        where tm.user_id = $1
                    ))
              )
        ), 0)
    end)::int as effective_role
from notes n
where n.id = $2
`

type GetNoteWithAccessParams struct {
	UserID uuid.UUID
	NoteID uuid.UUID
}

type GetNoteWithAccessRow struct {
	ID            uuid.UUID
	OwnerUserID   uuid.UUID
	Title         string
	Body          string
	Tags          []string
	Version       int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     *time.Time
	EffectiveRole int32
}

// GetNoteWithAccess fetches a note together with the caller's effective role,
// in one statement.
//
// One statement rather than fetch-then-check on purpose: a separate
// authorization query is a time-of-check-to-time-of-use gap, and it doubles
// the round trips on the hottest path in the service.
//
// The role is returned as an integer rank, not a name. Ordering role *names*
// in SQL sorts alphabetically, and "viewer" > "editor" -- a max() over names
// would silently promote every viewer on a note that carries both grants.
//
// deleted_at is returned rather than filtered. Callers decide: a read must
// treat a deleted note as absent, but restore has to find it.
func (q *Queries) GetNoteWithAccess(ctx context.Context, arg GetNoteWithAccessParams) (GetNoteWithAccessRow, error) {
	row := q.db.QueryRow(ctx, getNoteWithAccess, arg.UserID, arg.NoteID)
	var i GetNoteWithAccessRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Title,
		&i.Body,
		&i.Tags,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.EffectiveRole,
	)
	return i, err
}

const restoreNote = `-- name: RestoreNote :one
update notes
set deleted_at = null, updated_at = now(), version = version + 1
where id = $1 and deleted_at is not null
returning id, owner_user_id, title, body, tags, version, created_at, updated_at, deleted_at
`

type RestoreNoteRow struct {
	ID          uuid.UUID
	OwnerUserID uuid.UUID
	Title       string
	Body        string
	Tags        []string
	Version     int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   *time.Time
}

func (q *Queries) RestoreNote(ctx context.Context, id uuid.UUID) (RestoreNoteRow, error) {
	row := q.db.QueryRow(ctx, restoreNote, id)
	var i RestoreNoteRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Title,
		&i.Body,
		&i.Tags,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteNote = `-- name: SoftDeleteNote :execrows
update notes
set deleted_at = now(), updated_at = now(), version = version + 1
where id = $1 and deleted_at is null
`

// Soft delete. The note stays queryable for its owner and disappears for
// everyone it was shared with.
func (q *Queries) SoftDeleteNote(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteNote, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateNote = `-- name: UpdateNote :one
update notes
set title      = coalesce($1, title),
    body       = coalesce($2, body),
    tags       = coalesce($3, tags),
    version    = version + 1,
    updated_at = now()
where id = $4
  and version = $5
  and deleted_at is null
returning id, owner_user_id, title, body, tags, version, created_at, updated_at, deleted_at
`

type UpdateNoteParams struct {
	Title           *string
	Body            *string
	Tags            []string
	ID              uuid.UUID
	ExpectedVersion int32
}

type UpdateNoteRow struct {
	ID          uuid.UUID
	OwnerUserID uuid.UUID
	Title       string
	Body        string
	Tags        []string
	Version     int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   *time.Time
}

// UpdateNote applies a partial update under optimistic concurrency.
//
// The version predicate is what makes this safe: check and write are one
// atomic statement, so no explicit lock or transaction is needed. Zero rows
// affected means someone else committed first (or the note was deleted), and
// the caller re-reads to tell those apart.
func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (UpdateNoteRow, error) {
	row := q.db.QueryRow(ctx, updateNote,
		arg.Title,
		arg.Body,
		arg.Tags,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i UpdateNoteRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Title,
		&i.Body,
		&i.Tags,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
