// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shares.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteNoteShare = `-- name: DeleteNoteShare :execrows
delete from note_shares
where note_id = $1 and principal_type = $2 and principal_id = $3
`

type DeleteNoteShareParams struct {
	NoteID        uuid.UUID
	PrincipalType string
	PrincipalID   uuid.UUID
}

func (q *Queries) DeleteNoteShare(ctx context.Context, arg DeleteNoteShareParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNoteShare, arg.NoteID, arg.PrincipalType, arg.PrincipalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const isTeamMember = `-- name: IsTeamMember :one
select exists(
    select 1 from team_members where team_id = $1 and user_id = $2
)
`

type IsTeamMemberParams struct {
	TeamID uuid.UUID
	UserID uuid.UUID
}

// IsTeamMember gates sharing with a team the granter does not belong to.
func (q *Queries) IsTeamMember(ctx context.Context, arg IsTeamMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isTeamMember, arg.TeamID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listNoteShares = `-- name: ListNoteShares :many
select
    s.principal_type,
    s.principal_id,
    s.role,
    s.created_at,
    coalesce(u.display_name, t.name, '(deleted)') as principal_name,
    u.email as principal_email
from note_shares s
left join users u on s.principal_type = 'user' and u.id = s.principal_id
left join teams t on s.principal_type = 'team' and t.id = s.principal_id
where s.note_id = $1
order by s.principal_type, principal_name
`

type ListNoteSharesRow struct {
	PrincipalType  string
	PrincipalID    uuid.UUID
	Role           string
	CreatedAt      time.Time
	PrincipalName  string
	PrincipalEmail *string
}

// ListNoteShares resolves each principal's display name in the same query.
//
// A left join per principal type rather than two round trips: a share list is
// useless without names, and "who can see this note" is exactly the question a
// viewer asks.
func (q *Queries) ListNoteShares(ctx context.Context, noteID uuid.UUID) ([]ListNoteSharesRow, error) {
	rows, err := q.db.Query(ctx, listNoteShares, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNoteSharesRow{}
	for rows.Next() {
		var i ListNoteSharesRow
		if err := rows.Scan(
			&i.PrincipalType,
			&i.PrincipalID,
			&i.Role,
			&i.CreatedAt,
			&i.PrincipalName,
			&i.PrincipalEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const teamExists = `-- name: TeamExists :one
select exists(select 1 from teams where id = $1)
`

// TeamExists and UserExists validate a grant target before it is written.
//
// Needed because principal_id has no foreign key, so the database will happily
// accept a grant to a UUID that names nothing. Without these, a typo becomes a
// permanently dead grant row rather than a 404.
func (q *Queries) TeamExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, teamExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const upsertNoteShare = `-- name: UpsertNoteShare :one
insert into note_shares (note_id, principal_type, principal_id, role, granted_by)
values ($1, $2, $3, $4, $5)
on conflict (note_id, principal_type, principal_id)
    do update set role = excluded.role, granted_by = excluded.granted_by
returning note_id, principal_type, principal_id, role, granted_by, created_at
`

type UpsertNoteShareParams struct {
	NoteID        uuid.UUID
	PrincipalType string
	PrincipalID   uuid.UUID
	Role          string
	GrantedBy     uuid.UUID
}

func (q *Queries) UpsertNoteShare(ctx context.Context, arg UpsertNoteShareParams) (NoteShare, error) {
	row := q.db.QueryRow(ctx, upsertNoteShare,
		arg.NoteID,
		arg.PrincipalType,
		arg.PrincipalID,
		arg.Role,
		arg.GrantedBy,
	)
	var i NoteShare
	err := row.Scan(
		&i.NoteID,
		&i.PrincipalType,
		&i.PrincipalID,
		&i.Role,
		&i.GrantedBy,
		&i.CreatedAt,
	)
	return i, err
}

const userExists = `-- name: UserExists :one
select exists(select 1 from users where id = $1 and deleted_at is null)
`

func (q *Queries) UserExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
