// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addTeamMember = `-- name: AddTeamMember :one
insert into team_members (team_id, user_id, role)
values ($1, $2, $3)
on conflict (team_id, user_id) do update set role = excluded.role
returning team_id, user_id, role, created_at
`

type AddTeamMemberParams struct {
	TeamID uuid.UUID
	UserID uuid.UUID
	Role   string
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, addTeamMember, arg.TeamID, arg.UserID, arg.Role)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const countTeamAdmins = `-- name: CountTeamAdmins :one
select count(*) from team_members where team_id = $1 and role = 'admin'
`

// CountTeamAdmins backs the last-admin guard. Read inside the same
// transaction as the removal or demotion it protects, so two concurrent
// requests cannot each observe two admins and both proceed, leaving zero.
func (q *Queries) CountTeamAdmins(ctx context.Context, teamID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTeamAdmins, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTeam = `-- name: CreateTeam :one
insert into teams (name) values ($1)
returning id, name, created_at, updated_at
`

func (q *Queries) CreateTeam(ctx context.Context, name string) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :execrows
delete from teams where id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTeam, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTeamShareGrants = `-- name: DeleteTeamShareGrants :execrows
delete from note_shares
where principal_type = 'team' and principal_id = $1
`

// DeleteTeamShareGrants removes grants naming this team as a principal.
//
// Required because note_shares.principal_id has no foreign key -- it points at
// users or teams depending on principal_type, which Postgres cannot express --
// so dropping the team cascades nothing. A grant left behind would resolve
// against a reused UUID. Always runs in the same transaction as the delete.
func (q *Queries) DeleteTeamShareGrants(ctx context.Context, principalID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTeamShareGrants, principalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMembership = `-- name: GetMembership :one
select role from team_members
where team_id = $1 and user_id = $2
`

type GetMembershipParams struct {
	TeamID uuid.UUID
	UserID uuid.UUID
}

// GetMembership is the authorization check for every team operation.
func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (string, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.TeamID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getTeam = `-- name: GetTeam :one
select id, name, created_at, updated_at from teams where id = $1
`

func (q *Queries) GetTeam(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMyTeams = `-- name: ListMyTeams :many
select t.id, t.name, t.created_at, t.updated_at, tm.role
from teams t
join team_members tm on tm.team_id = t.id
where tm.user_id = $1
order by t.name
`

type ListMyTeamsRow struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Role      string
}

func (q *Queries) ListMyTeams(ctx context.Context, userID uuid.UUID) ([]ListMyTeamsRow, error) {
	rows, err := q.db.Query(ctx, listMyTeams, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyTeamsRow{}
	for rows.Next() {
		var i ListMyTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembers = `-- name: ListTeamMembers :many
select u.id, u.email, u.display_name, tm.role, tm.created_at
from team_members tm
join users u on u.id = tm.user_id
where tm.team_id = $1
order by tm.role, u.display_name
`

type ListTeamMembersRow struct {
	ID          uuid.UUID
	Email       string
	DisplayName string
	Role        string
	CreatedAt   time.Time
}

func (q *Queries) ListTeamMembers(ctx context.Context, teamID uuid.UUID) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamMembersRow{}
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamMember = `-- name: RemoveTeamMember :execrows
delete from team_members where team_id = $1 and user_id = $2
`

type RemoveTeamMemberParams struct {
	TeamID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeTeamMember, arg.TeamID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMemberRole = `-- name: SetMemberRole :execrows
update team_members set role = $3 where team_id = $1 and user_id = $2
`

type SetMemberRoleParams struct {
	TeamID uuid.UUID
	UserID uuid.UUID
	Role   string
}

func (q *Queries) SetMemberRole(ctx context.Context, arg SetMemberRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, setMemberRole, arg.TeamID, arg.UserID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTeam = `-- name: UpdateTeam :one
update teams set name = $2, updated_at = now()
where id = $1
returning id, name, created_at, updated_at
`

type UpdateTeamParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeam, arg.ID, arg.Name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
