// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
insert into users (email, password_hash, display_name)
values ($1, $2, $3)
returning id, email, password_hash, display_name, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	DisplayName  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUserShareGrants = `-- name: DeleteUserShareGrants :execrows
delete from note_shares
where principal_type = 'user' and principal_id = $1
`

// DeleteUserShareGrants removes the grants that name this user as a
// principal. This is the price of the polymorphic principal column: no foreign
// key covers it, so no cascade fires, and an orphaned grant would resolve
// against a reused UUID. Always runs in the same transaction as the delete.
func (q *Queries) DeleteUserShareGrants(ctx context.Context, principalID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserShareGrants, principalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findUserByExactEmail = `-- name: FindUserByExactEmail :one
select u.id, u.email, u.password_hash, u.display_name, u.created_at, u.updated_at, u.deleted_at from users u
where u.email = $1
  and u.deleted_at is null
  and (
    u.id = $2
    or exists (
      select 1
      from team_members caller
      join team_members target on target.team_id = caller.team_id
      where caller.user_id = $2
        and target.user_id = u.id
    )
  )
`

type FindUserByExactEmailParams struct {
	Email    string
	CallerID uuid.UUID
}

// FindUserByExactEmail backs share-target lookup. Exact match only, and
// scoped to people the caller already shares a team with: a general user
// directory is a data-harvesting surface, and enumeration costs nothing to
// close at design time.
func (q *Queries) FindUserByExactEmail(ctx context.Context, arg FindUserByExactEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, findUserByExactEmail, arg.Email, arg.CallerID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
select id, email, password_hash, display_name, created_at, updated_at, deleted_at from users
where id = $1 and deleted_at is null
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one

select id, email, password_hash, display_name, created_at, updated_at, deleted_at from users
where email = $1 and deleted_at is null
`

// Login and lookup paths filter deleted_at: a soft-deleted account must not
// authenticate, and must not be findable.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserForDisplay = `-- name: GetUserForDisplay :one
select id, email, password_hash, display_name, created_at, updated_at, deleted_at from users
where id = $1
`

// GetUserForDisplay includes soft-deleted rows on purpose. A note owned by a
// deleted user still has to render an owner, as a tombstone rather than a
// blank.
func (q *Queries) GetUserForDisplay(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserForDisplay, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :execrows
update users
set deleted_at = now(), updated_at = now()
where id = $1 and deleted_at is null
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
update users
set password_hash = $2, updated_at = now()
where id = $1 and deleted_at is null
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserProfile = `-- name: UpdateUserProfile :one
update users
set display_name = coalesce($1, display_name),
    email        = coalesce($2, email),
    updated_at   = now()
where id = $3 and deleted_at is null
returning id, email, password_hash, display_name, created_at, updated_at, deleted_at
`

type UpdateUserProfileParams struct {
	DisplayName *string
	Email       *string
	ID          uuid.UUID
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.DisplayName, arg.Email, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
