package store

import (
	"context"
	"encoding/base64"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"
)

// This is the one query that is NOT generated by sqlc, and the exception is
// deliberate.
//
// The endpoint takes optional filters, and sqlc's answer to dynamic predicates
// is `sqlc.narg` plus `WHERE ($1::uuid IS NULL OR owner_user_id = $1)`. That
// compiles, but the planner cannot use an index through an OR-NULL, so every
// filter combination degrades to a sequential scan of the notes table. The
// predicates here are appended only when the filter is actually present, so
// each query the planner sees is the narrow one it can index.
//
// Knowing where a tool stops fitting and stepping outside it explicitly is
// better than forcing every query through one mechanism.

// ListFilter is a parsed, validated query. Every field narrows the set the
// caller may already read -- nothing here can widen access. That invariant is
// what makes the endpoint safe to extend: a new filter is a new AND, never a
// new way in.
type ListFilter struct {
	UserID uuid.UUID

	Query        string     // full-text over title and body
	Tags         []string   // AND semantics
	Owner        *uuid.UUID // notes owned by this user, that I can see
	Team         *uuid.UUID // notes shared with this team, that I can see
	SharedWithMe bool       // excludes notes I own
	Deleted      bool       // owner-scoped; see below
	Limit        int32
	Cursor       *Cursor
}

// ListRow is one note plus the caller's role and its attachment count.
type ListRow struct {
	ID            uuid.UUID
	OwnerUserID   uuid.UUID
	Title         string
	Body          string
	Tags          []string
	Version       int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     *time.Time
	EffectiveRole int32
	Attachments   int64
	rank          float32
}

// Cursor is the position of the last row of the previous page.
//
// Keyset, not offset: offset pagination skips and duplicates rows whenever a
// concurrent insert shifts the window, which on a recency-ordered feed is
// constantly.
type Cursor struct {
	UpdatedAt time.Time
	ID        uuid.UUID
	Rank      float32 // only meaningful when the page was ordered by relevance
}

func (c Cursor) Encode() string {
	return base64.RawURLEncoding.EncodeToString([]byte(fmt.Sprintf(
		"%d|%s|%s", c.UpdatedAt.UnixNano(), c.ID, strconv.FormatFloat(float64(c.Rank), 'g', -1, 32),
	)))
}

func DecodeCursor(s string) (*Cursor, error) {
	raw, err := base64.RawURLEncoding.DecodeString(s)
	if err != nil {
		return nil, fmt.Errorf("malformed cursor")
	}
	parts := strings.Split(string(raw), "|")
	if len(parts) != 3 {
		return nil, fmt.Errorf("malformed cursor")
	}
	nanos, err := strconv.ParseInt(parts[0], 10, 64)
	if err != nil {
		return nil, fmt.Errorf("malformed cursor")
	}
	id, err := uuid.Parse(parts[1])
	if err != nil {
		return nil, fmt.Errorf("malformed cursor")
	}
	rank, err := strconv.ParseFloat(parts[2], 32)
	if err != nil {
		return nil, fmt.Errorf("malformed cursor")
	}
	return &Cursor{UpdatedAt: time.Unix(0, nanos).UTC(), ID: id, Rank: float32(rank)}, nil
}

// ListNotes returns one page of notes the caller may read.
func (s *Store) ListNotes(ctx context.Context, f ListFilter) ([]ListRow, *Cursor, error) {
	var args []any
	arg := func(v any) string {
		args = append(args, v)
		return "$" + strconv.Itoa(len(args))
	}

	user := arg(f.UserID)

	// The same role resolution as the single-note read, inlined so the list
	// and the detail view can never disagree about what a caller may do.
	//
	// Resolved once per row against an index on (principal_type, principal_id),
	// not per row with a second round trip: this is the whole cost of choosing
	// an ACL table over a denormalised column, and it is paid here.
	roleExpr := `
		(case
			when n.owner_user_id = ` + user + ` then 3
			else coalesce((
				select max(case s.role when 'editor' then 2 when 'viewer' then 1 else 0 end)
				from note_shares s
				where s.note_id = n.id
				  and ((s.principal_type = 'user' and s.principal_id = ` + user + `)
				    or (s.principal_type = 'team' and s.principal_id in (
				          select tm.team_id from team_members tm where tm.user_id = ` + user + `)))
			), 0)
		end)::int`

	var where []string

	// The authorization predicate. Everything else narrows this.
	where = append(where, `(
		n.owner_user_id = `+user+`
		or exists (
			select 1 from note_shares s
			where s.note_id = n.id
			  and ((s.principal_type = 'user' and s.principal_id = `+user+`)
			    or (s.principal_type = 'team' and s.principal_id in (
			          select tm.team_id from team_members tm where tm.user_id = `+user+`)))
		))`)

	// Deleted notes are owner-scoped. A note deleted by its owner must stay
	// invisible to everyone it was shared with, so this is not merely a
	// visibility toggle -- it also restricts to notes you own.
	if f.Deleted {
		where = append(where, "n.deleted_at is not null")
		where = append(where, "n.owner_user_id = "+user)
	} else {
		where = append(where, "n.deleted_at is null")
	}

	if f.Owner != nil {
		where = append(where, "n.owner_user_id = "+arg(*f.Owner))
	}
	if f.SharedWithMe {
		where = append(where, "n.owner_user_id <> "+user)
	}
	if f.Team != nil {
		// Scoped to teams the caller belongs to. Without the membership check
		// this would report whether an arbitrary team has notes, which is a
		// slow read of another team's shape.
		where = append(where, `exists (
			select 1 from note_shares s
			join team_members tm on tm.team_id = s.principal_id and tm.user_id = `+user+`
			where s.note_id = n.id and s.principal_type = 'team' and s.principal_id = `+arg(*f.Team)+`
		)`)
	}
	if len(f.Tags) > 0 {
		// @> is the containment operator, which the GIN index on tags serves.
		where = append(where, "n.tags @> "+arg(f.Tags))
	}

	byRelevance := f.Query != ""
	var rankExpr string
	if byRelevance {
		q := arg(f.Query)
		// websearch_to_tsquery accepts what people actually type -- quoted
		// phrases, OR, leading minus -- and does not raise on syntax a user
		// invents, which plainto_tsquery and to_tsquery both do.
		where = append(where, "n.search_tsv @@ websearch_to_tsquery('english', "+q+")")
		rankExpr = "ts_rank(n.search_tsv, websearch_to_tsquery('english', " + q + "))"
	} else {
		rankExpr = "0::real"
	}

	// Keyset predicate. Row comparison rather than an unrolled OR chain,
	// because Postgres can drive an index scan directly from (a, b) < (x, y).
	if f.Cursor != nil {
		if byRelevance {
			where = append(where, "("+rankExpr+", n.id) < ("+arg(f.Cursor.Rank)+", "+arg(f.Cursor.ID)+")")
		} else {
			where = append(where, "(n.updated_at, n.id) < ("+arg(f.Cursor.UpdatedAt)+", "+arg(f.Cursor.ID)+")")
		}
	}

	order := "n.updated_at desc, n.id desc"
	if byRelevance {
		order = rankExpr + " desc, n.id desc"
	}

	// One extra row, to know whether a next page exists without a second
	// count query -- which on a filtered, authorized set would cost as much as
	// the page itself.
	limit := f.Limit
	sql := `
		select n.id, n.owner_user_id, n.title, n.body, n.tags, n.version,
		       n.created_at, n.updated_at, n.deleted_at,
		       ` + roleExpr + ` as effective_role,
		       (select count(*) from attachments a
		         where a.note_id = n.id and a.status = 'ready') as attachment_count,
		       ` + rankExpr + `::real as rank
		from notes n
		where ` + strings.Join(where, "\n  and ") + `
		order by ` + order + `
		limit ` + arg(limit+1)

	rows, err := s.Pool.Query(ctx, sql, args...)
	if err != nil {
		return nil, nil, fmt.Errorf("listing notes: %w", err)
	}
	defer rows.Close()

	out := make([]ListRow, 0, limit)
	for rows.Next() {
		var r ListRow
		if err := rows.Scan(
			&r.ID, &r.OwnerUserID, &r.Title, &r.Body, &r.Tags, &r.Version,
			&r.CreatedAt, &r.UpdatedAt, &r.DeletedAt,
			&r.EffectiveRole, &r.Attachments, &r.rank,
		); err != nil {
			return nil, nil, fmt.Errorf("scanning note: %w", err)
		}
		out = append(out, r)
	}
	if err := rows.Err(); err != nil {
		return nil, nil, err
	}

	var next *Cursor
	if int32(len(out)) > limit {
		out = out[:limit]
		last := out[len(out)-1]
		next = &Cursor{UpdatedAt: last.UpdatedAt, ID: last.ID, Rank: last.rank}
	}
	return out, next, nil
}
